import React from "react";
import { FileProps, Item } from "./FileManager";
import { ClipboardProps } from "./Utils/ActionUtils";
import { InterfaceFileManagerAPI } from "./apis/InterfaceFileManagerAPI";
type MenuContextProps = {
    API: InterfaceFileManagerAPI;
    disk: string;
    view: string;
    clipboard?: ClipboardProps;
    current?: Item;
    currents?: Item[];
    data: Item;
    row?: any;
    table?: any;
    props?: any;
    handleMultipleClick: (data: Item[]) => void;
    handleOneClick: (data: Item) => void;
    handleDoubleClick: (data: Item) => void;
    handleDownload: (data: Item) => void;
    handleCopy: (data: any) => void;
    handleCut: (data: any) => void;
    handlePaste: () => void;
    toggleModalDetail: (data: Item) => void;
    togglePreview: (data: FileProps) => void;
    toggleRename: (data: Item) => void;
    toggleEdit: (data: Item) => void;
    toggleDelete: (data: Item) => void;
};
declare const MenuContext: React.FC<MenuContextProps>;
export default MenuContext;
