import { AxiosResponse } from "axios";
export interface InterfaceFileManagerAPI {
    initialize(): Promise<AxiosResponse>;
    content(data: any): Promise<AxiosResponse>;
    tree(data: any): Promise<AxiosResponse>;
    selectDisk(data: any): Promise<AxiosResponse>;
    upload(data: any): Promise<AxiosResponse>;
    delete(data: any): Promise<AxiosResponse>;
    paste(data: any): Promise<AxiosResponse>;
    rename(data: any): Promise<AxiosResponse>;
    download(data: any): Promise<AxiosResponse>;
    thumbnails(data: any): Promise<AxiosResponse>;
    preview(data: any): Promise<AxiosResponse>;
    url(data: any): Promise<AxiosResponse>;
    info(data: any): Promise<AxiosResponse>;
    listshare(data: any): Promise<AxiosResponse>;
    share(data: any): Promise<AxiosResponse>;
    unshare(data: any): Promise<AxiosResponse>;
    checkExist(data: any): Promise<AxiosResponse>;
    createDirectory(data: any): Promise<AxiosResponse>;
    createFile(data: any): Promise<AxiosResponse>;
    updateFile(data: any): Promise<AxiosResponse>;
    streamFile(data: any): Promise<AxiosResponse>;
    zip(data: any): Promise<AxiosResponse>;
    unzip(data: any): Promise<AxiosResponse>;
    ckeditor(): Promise<AxiosResponse>;
    tinymce(): Promise<AxiosResponse>;
    tinymce5(): Promise<AxiosResponse>;
    summernote(): Promise<AxiosResponse>;
    fmButton(): Promise<AxiosResponse>;
}
